server:
  port: ${mongo_server_port}
eureka:
  client:
    service-url:
      defaultZone: ${eureka_host}
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    prefer-ip-address: true
spring:
  application:
    name: mongo-server
management:
  endpoint:
    health:
      enabled: true