server:
  port: ${mongo_server_port}
eureka:
  client:
    service-url:
      defaultZone: ${eureka_host}
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    prefer-ip-address: ${eureka_prefer_ip}
    hostname: ${mongo_server_hostname}
spring:
  application:
    name: mongo-server
  data:
    mongodb:
      host: ${mongo_host}
      port: ${mongo_port}
      username: ${mongo_user}
      password: ${mongo_password}
management:
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
mongo:
  host: ${mongo_host}
  port: ${mongo_port}
  user: ${mongo_user}
  password: ${mongo_password}
  truststore:
    path: ${mongo_truststore_path}
    password: ${mongo_truststore_password}
  keystore:
    path: ${mongo_keystore_path}
    password: ${mongo_keystore_password}
    key-password: ${mongo_keystore_key_password}