version: '3.6'

services:
  eureka:
    build: ../eureka-server/.
    ports:
      - "7777:7777"
    environment:
      - eureka_server_port=7777
      - eureka_hostname=localhost
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:7777/actuator/health 2>&1 | grep UP || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
    volumes:
      - type: bind
        source: /var/lib/docker/volumes/logback/_data
        target: /mnt/
      - type: bind
        source: /var/lib/docker/volumes/logs/_data
        target: /mnt/logs
  ignite:
    build: ../ignite-server/.
    ports:
      - "11000:10000"
    environment:
      - ignite_server_port=10000
      - eureka_host=http://eureka:7777/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:10000/actuator/health 2>&1 | grep UP || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
    volumes:
      - type: bind
        source: /var/lib/docker/volumes/logback/_data
        target: /mnt/
      - type: bind
        source: /var/lib/docker/volumes/logs/_data
        target: /mnt/logs
  mongo:
    build: ../mongo-server/.
    ports:
      - "12000:10000"
    environment:
      - mongo_server_port=13000
      - mongo_host=host.docker.internal
      - mongo_port=27017
      - eureka_host=http://eureka:7777/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:10000/actuator/health 2>&1 | grep UP || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
    volumes:
      - type: bind
        source: /var/lib/docker/volumes/logback/_data
        target: /mnt/
      - type: bind
        source: /var/lib/docker/volumes/logs/_data
        target: /mnt/logs
  posgre:
    build: ../postgre-server/.
    environment:
      - postgres_server_port=12000
      - postgres_host=host.docker.internal
      - postgres_port=5432
      - postgres_db=postgres
      - postgres_user=test
      - postgres_password=test
      - eureka_host=http://eureka:7777/eureka
      - postgres_min_pool_size=2
      - postgres_max_pool_size=5
      - postgres_max_idle_time=180
      - postgres_idle_connection_test_period=10
      - postgres_test_connection_on_checkout=true
      - postgres_preferred_test_query=select 1
    ports:
      - "13000:10000"
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:10000/actuator/health 2>&1 | grep UP || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
    volumes:
      - type: bind
        source: /var/lib/docker/volumes/logback/_data
        target: /mnt/
      - type: bind
        source: /var/lib/docker/volumes/logs/_data
        target: /mnt/logs
  web:
    build: ../addressbook-main/.
    ports:
      - "10000:9000"
    environment:
      - web_server_port=9000
      - dao_implementation=IGNITE-SERVER
      - jwt_secret=q1w2e3r4
      - key_alias=localhost
      - keystore_password=q1w2e3r4
      - keystore_path=/mnt/certs/keystore.jks
      - truststore_password=q1w2e3r4
      - truststore_path=/mnt/certs/truststore.jks
      - key_password=q1w2e3r4
      - eureka_host=http://eureka:7777/eureka
    restart: on-failure
    volumes:
      - type: bind
        source: /var/lib/docker/volumes/certs/_data
        target: /mnt/certs
      - type: bind
        source: /var/lib/docker/volumes/logback/_data
        target: /mnt/
      - type: bind
        source: /var/lib/docker/volumes/logs/_data
        target: /mnt/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:9000/actuator/health 2>&1 | grep UP || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
    depends_on:
      - eureka
      - posgre
      - mongo
      - ignite
    links:
      - eureka
      - posgre
      - mongo
      - ignite