kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-mongo-app-settings
  labels:
    app: {{namespace}}-mongo
data:
  eureka_host: "{{eureka_client_host}}"
  eureka_prefer_ip: "{{eureka_prefer_ip}}"
  mongo_server_hostname: "{{mongo_server_hostname}}"
  mongo_server_port: "{{mongo_server_port}}"
  mongo_host: "{{mongo_db_host}}"
  mongo_port: "{{mongo_db_port}}"