kind: Deployment
apiVersion: apps/v1
metadata:
  name: dp-mongo-app
  labels:
    app: {{namespace}}-mongo
spec:
  replicas: {{mongo_replica_count}}
  selector:
    matchLabels:
      app: {{namespace}}-mongo
  template:
    metadata:
      labels:
        app: {{namespace}}-mongo
    spec:
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 60
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: {{mongo_cpu_limit}}
              memory: {{mongo_mem_limit}}
            requests:
              cpu: {{mongo_cpu_req}}
              memory: {{mongo_mem_req}}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{mongo_server_port}}
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{mongo_server_port}}
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{mongo_server_port}}
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 10
          terminationMessagePath: /dev/termination-log
          name: mongo-app
          securityContext:
            readOnlyRootFilesystem: false
          envFrom:
            - configMapRef:
                name: cm-mongo-app-settings
          ports:
            - name: tcp-{{mongo_server_port}}
              containerPort: {{mongo_server_port}}
              protocol: TCP
          imagePullPolicy: Never
          volumeMounts:
            - name: logsshare
              mountPath: /mnt/logs
            - name: logback
              readOnly: true
              mountPath: /mnt/
          terminationMessagePolicy: File
          image: {{mongo_image}}
      dnsPolicy: ClusterFirst
      volumes:
        - name: logback
          configMap:
            defaultMode: 256
            name: cm-mongo-logback
            items:
              - key: logback.xml
                path: logback.xml
        - name: logsshare
          emptyDir: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 600