apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gw-mongo-database
spec:
  selector:
    istio: {{namespace}}-egress
  servers:
    - hosts:
        - {{mongo_db_host}}
      port:
        name: tcp-{{mongo_db_port}}
        number: {{mongo_db_port}}
        protocol: TCP