kubernetes_host_api: "https://localhost:6443"
namespace: "default"
validate_certs: false
path_to_templates: "../templates"
k8s_auth_api_key: eyJhbGciOiJSUzI1NiIsImtpZCI6IkhWR096cGt5aDJQTDFXWmdrQWk5VkNjR3E0Vzl3cV9lX1ZidjVVSHRkTGMifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNjU5MTczMjYzLCJpYXQiOjE2NTkxNjk2NjMsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJhZG1pbi11c2VyIiwidWlkIjoiOGRhOTQ0OWMtNjkyMC00NGY2LWI1ZWItOWEzNzg3MTk5MzQyIn19LCJuYmYiOjE2NTkxNjk2NjMsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlcm5ldGVzLWRhc2hib2FyZDphZG1pbi11c2VyIn0.F8AExwH2pZXxtkP0eezjggqG_nRpMkqoHHabowfZTO7LsTHx5TRJIcRCcyvykwo2dKW63EfL2JXlysNCF5T0ZveOW7hgHc0Xf7qFqMXZptL7V9-QUhsoGieeZfTd9KNdBdNjg8Zxs0m_BwdDuHE09Wn4D8iI5fhQevvpMZhEIcH42uqJv6iyeksajKPo4VonKouS5ksKJXco03NKo5V-l_ZeOimWvB3YTtkot3bn12PiAl96TJO07BVgZMKq7MxrStjg3FsJBolaLbsyQKdQ91vlYTBjWM4OJFzd98tS0H1wy10INEqoabrMkMT99jv835FAow23-0EpNrf1ZAhf8A
without_debug: false

# Eureka settings
eureka_hostname: localhost
eureka_server_port: 7777
eureka_replica_count: 1
eureka_cpu_limit: 2
eureka_mem_limit: 6000Mi
eureka_cpu_req: 2
eureka_mem_req: 6000Mi
eureka_image: addressbook_eureka:latest

