kubernetes_host_api: "https://localhost:6443"
namespace: "default"
validate_certs: false
path_to_templates: "../templates"
k8s_auth_api_key: <<insert token here>>
without_debug: false

# Eureka settings
eureka_hostname: localhost
eureka_server_port: 7777
eureka_replica_count: 1
eureka_cpu_limit: 2
eureka_mem_limit: 6000Mi
eureka_cpu_req: 2
eureka_mem_req: 6000Mi
eureka_image: addressbook_eureka:latest
eureka_client_host: http://svc-eureka-api:7777/eureka

# Ignite server settings
ignite_server_port: 10000
ignite_replica_count: 1
ignite_cpu_limit: 3
ignite_mem_limit: 8000Mi
ignite_cpu_req: 3
ignite_mem_req: 8000Mi
ignite_image: addressbook_db:latest

# Web application settings
web_server_port: 9000
web_replica_count: 1
web_cpu_limit: 2
web_mem_limit: 5000Mi
web_cpu_req: 2
web_mem_req: 5000Mi
web_keystore_path:  /opt/certs/web/keystore.jks
web_truststore_path:  /opt/certs/web/truststore.jks
web_image: addressbook_web:latest
web_dao_implementation: IGNITE-SERVER
web_route_host: demo.localdev.me