kubernetes_host_api: "https://localhost:6443"
namespace: "default"
validate_certs: false
path_to_templates: "../templates"
k8s_auth_api_key: eyJhbGciOiJSUzI1NiIsImtpZCI6IkhWR096cGt5aDJQTDFXWmdrQWk5VkNjR3E0Vzl3cV9lX1ZidjVVSHRkTGMifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNjU5MjAwNzU2LCJpYXQiOjE2NTkxOTcxNTYsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJhZG1pbi11c2VyIiwidWlkIjoiOGRhOTQ0OWMtNjkyMC00NGY2LWI1ZWItOWEzNzg3MTk5MzQyIn19LCJuYmYiOjE2NTkxOTcxNTYsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlcm5ldGVzLWRhc2hib2FyZDphZG1pbi11c2VyIn0.IKSDlyndH345Z-CCosWFduDnkSiYHMa2sIundg2e7hljLFmGwiQ39fK-5my5CT1H5a6rTk6Mr5qh1P1Lb61VLRXvTV_SPeJ0_4T6_-TEYPY_06bssNZgxJTqs9C4KKrcjCnyDi3rXkG5e-3Q8V4l293p4Cy4lyQDKm9HF32s_a8RJ0NzjqlXjMysxcwgQ8_53_u6h2-4RArose4m2W-lRgbt65ZGT0NE691rNiaC-6xFBBTiOqtgS8RxBj-wdbCf1twJX_dndcOtgtfEb3dTxsil_34-jU39WnYscKG5kKp7aXp4tKbVx8mtP-_t69GjlvBl3M-vkBgosdHfL0yCqA
without_debug: false

# Eureka settings
eureka_hostname: localhost
eureka_server_port: 7777
eureka_replica_count: 1
eureka_cpu_limit: 2
eureka_mem_limit: 6000Mi
eureka_cpu_req: 2
eureka_mem_req: 6000Mi
eureka_image: addressbook_eureka:latest

eureka_client_host: http://svc-eureka-api:7777/eureka

ignite_server_port: 10000
ignite_replica_count: 1
ignite_cpu_limit: 3
ignite_mem_limit: 8000Mi
ignite_cpu_req: 3
ignite_mem_req: 8000Mi
ignite_image: addressbook_db:latest

web_server_port: 9000
web_replica_count: 1
web_cpu_limit: 2
web_mem_limit: 5000Mi
web_cpu_req: 2
web_mem_req: 5000Mi
web_keystore_path:  /opt/certs/web/keystore.jks
web_truststore_path:  /opt/certs/web/truststore.jks
web_image: addressbook_web:latest
web_dao_implementation: IGNITE-SERVER