validate_certs: false
path_to_templates: "../templates"
without_debug: false

# Eureka settings
eureka_hostname: localhost
eureka_replica_count: 1
eureka_cpu_limit: 2
eureka_mem_limit: 6000Mi
eureka_cpu_req: 2
eureka_mem_req: 6000Mi
eureka_prefer_ip: false

# Ignite server settings
ignite_server_port: 10000
ignite_server_hostname: svc-ignite-api
ignite_replica_count: 1
ignite_cpu_limit: 3
ignite_mem_limit: 8000Mi
ignite_cpu_req: 3
ignite_mem_req: 8000Mi

# Mongo server settings
mongo_server_hostname: svc-mongo-api
mongo_replica_count: 1
mongo_cpu_limit: 2
mongo_mem_limit: 4000Mi
mongo_cpu_req: 2
mongo_mem_req: 4000Mi

# PostgreSQL server settings
postgres_server_hostname: svc-postgre-api
postgres_replica_count: 1
postgres_cpu_limit: 2
postgres_mem_limit: 4000Mi
postgres_cpu_req: 2
postgres_mem_req: 4000Mi
postgres_min_pool_size: 2
postgres_max_pool_size: 5
postgres_max_idle_time: 180000
postgres_idle_connection_test_period: 10000
postgres_preferred_test_query: select 1

# Web application settings
web_replica_count: 1
web_cpu_limit: 2
web_mem_limit: 5000Mi
web_cpu_req: 2
web_mem_req: 5000Mi
web_keystore_path:  /opt/certs/web/keystore.jks
web_truststore_path:  /opt/certs/web/truststore.jks
storage_path: /mnt/docs

#Istio Ingress & Egress settings
ingressgateway_name: dp-addressbook-app-ingress
ingressgateway_certs_secret_name: secret-ingressgateway-certs
ingressgateway_ca_certs_secret_name: secret-ingressgateway-ca-certs
ingressgateway_certs_mount_path: /etc/istio/ingressgateway-certs
ingressgateway_ca_certs_mount_path: /etc/istio/ingressgateway-ca-certs

egressgateway_name: dp-addressbook-app-egress

# Istio Proxy sidecar resource settings
sidecar_cpu_istio_req: 100m
sidecar_cpu_istio_lim: 100m
sidecar_mem_istio_req: 1000Mi
sidecar_mem_istio_lim: 1000Mi

# Fluent Bit sidecar resource settings
cpu_fb_limit: 200m
mem_fb_limit: 32Mi
cpu_fb_req: 200m
mem_fb_req: 32Mi