kubernetes_host_api: "https://localhost:6443"
namespace: "default"
validate_certs: false
path_to_templates: "../templates"
k8s_auth_api_key: eyJhbGciOiJSUzI1NiIsImtpZCI6IkhWR096cGt5aDJQTDFXWmdrQWk5VkNjR3E0Vzl3cV9lX1ZidjVVSHRkTGMifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNjU5MTgyMTg5LCJpYXQiOjE2NTkxNzg1ODksImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJhZG1pbi11c2VyIiwidWlkIjoiOGRhOTQ0OWMtNjkyMC00NGY2LWI1ZWItOWEzNzg3MTk5MzQyIn19LCJuYmYiOjE2NTkxNzg1ODksInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlcm5ldGVzLWRhc2hib2FyZDphZG1pbi11c2VyIn0.GqH7huzogSKowfRHW5XWpxWJ3DQ9i7PxFWEbMXkdnWkH2O41Q6GaFynN_FQz1f25H8RjRc2-wq7gdfgny_OtNk98Hy8mStiKIQk1VTfzRIp97DJoyKcrTTOt2QmeCDP1x78rd7ismaOyq9ozSvy45lfv4FrBiPNaVuwhIf8INS3RECT6M74DrA3Sij6rl8vZqpuRNUl0UU4y14fIHitaNLAwuZss6WyYRDT1bRsXSSbc7MaeRfw4Zr51z4XRi3u0HWDUgnOl8PHMMAZILqoGVBcWquoPJhsi6WQEbPI-3hTH1jblrpoJLRvQjW_Evb5OYLjaS2zGXAqgfH5NrB_15g
without_debug: false

# Eureka settings
eureka_hostname: localhost
eureka_server_port: 7777
eureka_replica_count: 1
eureka_cpu_limit: 2
eureka_mem_limit: 6000Mi
eureka_cpu_req: 2
eureka_mem_req: 6000Mi
eureka_image: addressbook_eureka:latest

eureka_client_host: http://svc-eureka-api:7777/eureka

ignite_server_port: 10000
ignite_replica_count: 1
ignite_cpu_limit: 3
ignite_mem_limit: 8000Mi
ignite_cpu_req: 3
ignite_mem_req: 8000Mi
ignite_image: addressbook_db:latest