# General settings
kubernetes_host_api: "https://localhost:6443"
namespace: "default"
validate_certs: false
path_to_templates: "../templates"
k8s_auth_api_key: <<insert token here>>
without_debug: false

# Eureka settings
eureka_hostname: localhost
eureka_server_port: 7777
eureka_replica_count: 1
eureka_cpu_limit: 2
eureka_mem_limit: 6000Mi
eureka_cpu_req: 2
eureka_mem_req: 6000Mi
eureka_image: addressbook_eureka:latest
eureka_client_host: http://svc-eureka-api:7777/eureka
eureka_prefer_ip: false

# Ignite server settings
ignite_server_port: 10000
ignite_server_hostname: svc-ignite-api
ignite_replica_count: 1
ignite_cpu_limit: 3
ignite_mem_limit: 8000Mi
ignite_cpu_req: 3
ignite_mem_req: 8000Mi
ignite_image: addressbook_ignite:latest

# Mongo server settings
mongo_server_port: 13000
mongo_server_hostname: svc-mongo-api
mongo_replica_count: 1
mongo_cpu_limit: 2
mongo_mem_limit: 4000Mi
mongo_cpu_req: 2
mongo_mem_req: 4000Mi
mongo_image: addressbook_mongo:latest
mongo_db_host: host.docker.internal
mongo_db_port: 11112
mongo_db_ip: 192.168.65.2
external_mongo_db_port: 27017

# PostgreSQL server settings
postgres_server_port: 12000
postgres_server_hostname: svc-postgre-api
postgres_replica_count: 1
postgres_cpu_limit: 2
postgres_mem_limit: 4000Mi
postgres_cpu_req: 2
postgres_mem_req: 4000Mi
postgres_image: addressbook_postgre:latest
external_postgres_port: 5432
postgres_port: 11111
postgres_host: host.docker.internal
postgres_ip: 192.168.65.2
postgres_db: postgres
postgres_min_pool_size: 2
postgres_max_pool_size: 5
postgres_max_idle_time: 180
postgres_idle_connection_test_period: 10
postgres_test_connection_on_checkout: true
postgres_preferred_test_query: select 1

# Web application settings
web_server_port: 9000
web_replica_count: 1
web_cpu_limit: 2
web_mem_limit: 5000Mi
web_cpu_req: 2
web_mem_req: 5000Mi
web_ssl_enabled: true
web_keystore_path:  /opt/certs/web/keystore.jks
web_truststore_path:  /opt/certs/web/truststore.jks
web_image: addressbook_web:latest
web_dao_implementation: IGNITE-SERVER
web_route_host: simple-https.localdev.me
web_istio_route_host: istio-https.localdev.me

#Istio Ingress & Egress settings
istio_cp_main: istiod
istio_control_plane: istio-system
proxy_image: docker.io/istio/proxyv2:1.14.3

ingressgateway_name: dp-addressbook-app-ingress
ingressgateway_certs_secret_name: secret-ingressgateway-certs
ingressgateway_ca_certs_secret_name: secret-ingressgateway-ca-certs
ingressgateway_certs_mount_path: /etc/istio/ingressgateway-certs
ingressgateway_ca_certs_mount_path: /etc/istio/ingressgateway-ca-certs

egressgateway_name: dp-addressbook-app-egress

sidecar_cpu_istio_req: 100m
sidecar_cpu_istio_lim: 100m
sidecar_mem_istio_req: 1000Mi
sidecar_mem_istio_lim: 1000Mi