kind: Deployment
apiVersion: apps/v1
metadata:
  name: dp-web-app
  labels:
    app: {{namespace}}-web
  annotations:
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/proxyCPU: {{sidecar_cpu_istio_req}}
    sidecar.istio.io/proxyCPULimit: {{sidecar_cpu_istio_lim}}
    sidecar.istio.io/proxyMemory: {{sidecar_mem_istio_req}}
    sidecar.istio.io/proxyMemoryLimit: {{sidecar_mem_istio_lim}}
spec:
  replicas: {{web_replica_count}}
  selector:
    matchLabels:
      app: {{namespace}}-web
  template:
    metadata:
      labels:
        app: {{namespace}}-web
    spec:
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 60
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: {{web_cpu_limit}}
              memory: {{web_mem_limit}}
            requests:
              cpu: {{web_cpu_req}}
              memory: {{web_mem_req}}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{web_server_port}}
{% if web_ssl_enabled %}
              scheme: HTTPS
{% else %}
              scheme: HTTP
{% endif %}
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{web_server_port}}
{% if web_ssl_enabled %}
              scheme: HTTPS
{% else %}
              scheme: HTTP
{% endif %}
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{web_server_port}}
{% if web_ssl_enabled %}
              scheme: HTTPS
{% else %}
              scheme: HTTP
{% endif %}
            failureThreshold: 30
            periodSeconds: 10
          terminationMessagePath: /dev/termination-log
          name: web-app
          securityContext:
            readOnlyRootFilesystem: false
          envFrom:
            - configMapRef:
                name: cm-web-app-settings
            - secretRef:
                name: secret-web-app
          ports:
            - name: tcp-{{web_server_port}}
              containerPort: {{web_server_port}}
              protocol: TCP
          imagePullPolicy: Never
          volumeMounts:
            - name: web-certs
              readOnly: true
              mountPath: /opt/certs/web/
            - name: logsshare
              mountPath: /mnt/logs
            - name: logback
              readOnly: true
              mountPath: /mnt/
          terminationMessagePolicy: File
          image: {{web_image}}
      dnsPolicy: ClusterFirst
      volumes:
        - name: logback
          configMap:
            defaultMode: 256
            name: cm-web-logback
            items:
              - key: logback.xml
                path: logback.xml
        - name: logsshare
          emptyDir: {}
        - name: web-certs
          secret:
            secretName: web-secret
            items:
              - key: keystore.jks
                path: keystore.jks
              - key: truststore.jks
                path: truststore.jks
            defaultMode: 256
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 600