apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: documents
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi