- name: "Get files from {{ path_to_templates }}/web"
  find:
    paths: "{{ path_to_templates }}/web"
    patterns: "*.y*ml"
    recurse: no
    file_type: file
  register: found_directories

- name: Get files path only
  set_fact:
    files_list_web: "{{ files_list_web|default([]) + [ {'path': item.path} ] }}"
  loop: "{{ found_directories.files }}"
  no_log: "{{ without_debug }}"

- name: Deploy .yaml to k8s
  k8s:
    state: present
    definition: "{{ lookup('template', '{{ item.path }}') | from_yaml }}"
    host: "{{ kubernetes_host_api }}"
    namespace: "{{ namespace }}"
    api_key: "{{ k8s_auth_api_key }}"
    validate_certs: "{{ validate_certs }}"
  register: result
  with_items: "{{ files_list_web }}"