kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-postgre-app-settings
  labels:
    app: {{namespace}}-postgre
data:
  eureka_host: "{{eureka_client_host}}"
  postgres_server_port: "{{postgres_server_port}}"
  postgres_url: "{{postgres_url}}"
  postgres_min_pool_size: "{{postgres_min_pool_size}}"
  postgres_max_pool_size: "{{postgres_max_pool_size}}"
  postgres_max_idle_time: "{{postgres_max_idle_time}}"
  postgres_idle_connection_test_period: "{{postgres_idle_connection_test_period}}"
  postgres_test_connection_on_checkout: "{{postgres_test_connection_on_checkout}}"
  postgres_preferred_test_query: "{{postgres_preferred_test_query}}"