kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-postgre-app-settings
  labels:
    app: {{namespace}}-postgre
data:
  eureka_host: "{{eureka_client_host}}"
  eureka_prefer_ip: "{{eureka_prefer_ip}}"
  postgres_server_port: "{{postgres_server_port}}"
  postgres_server_hostname: "{{postgres_server_hostname}}"
  postgres_host: "{{postgres_host}}"
  postgres_port: "{{postgres_port}}"
  postgres_db: "{{postgres_db}}"
  postgres_cert: "{{postgres_cert}}"
  postgres_key: "{{postgres_key}}"
  postgres_min_pool_size: "{{postgres_min_pool_size}}"
  postgres_max_pool_size: "{{postgres_max_pool_size}}"
  postgres_max_idle_time: "{{postgres_max_idle_time}}"
  postgres_idle_connection_test_period: "{{postgres_idle_connection_test_period}}"
  postgres_preferred_test_query: "{{postgres_preferred_test_query}}"
  java_opts: "{{postgres_java_opts}}"