kind: Deployment
apiVersion: apps/v1
metadata:
  name: dp-postgre-app
  labels:
    app: {{namespace}}-postgre
  annotations:
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/proxyCPU: {{sidecar_cpu_istio_req}}
    sidecar.istio.io/proxyCPULimit: {{sidecar_cpu_istio_lim}}
    sidecar.istio.io/proxyMemory: {{sidecar_mem_istio_req}}
    sidecar.istio.io/proxyMemoryLimit: {{sidecar_mem_istio_lim}}
spec:
  replicas: {{postgres_replica_count}}
  selector:
    matchLabels:
      app: {{namespace}}-postgre
  template:
    metadata:
      labels:
        app: {{namespace}}-postgre
    spec:
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 60
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: {{postgres_cpu_limit}}
              memory: {{postgres_mem_limit}}
            requests:
              cpu: {{postgres_cpu_req}}
              memory: {{postgres_mem_req}}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{postgres_server_port}}
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{postgres_server_port}}
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{postgres_server_port}}
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 10
          terminationMessagePath: /dev/termination-log
          name: postgre-app
          securityContext:
            readOnlyRootFilesystem: true
          envFrom:
            - configMapRef:
                name: cm-postgre-app-settings
            - secretRef:
                name: secret-postgres-app
          ports:
            - name: tcp-{{postgres_server_port}}
              containerPort: {{postgres_server_port}}
              protocol: TCP
          imagePullPolicy: Never
          volumeMounts:
            - name: db-certs
              readOnly: true
              mountPath: /opt/certs/db/
            - name: logsshare
              mountPath: /mnt/logs
            - name: logback
              readOnly: true
              mountPath: /mnt/
          terminationMessagePolicy: File
          image: {{postgres_image}}
      dnsPolicy: ClusterFirst
      volumes:
        - name: db-certs
          secret:
            secretName: postgres-secret
            items:
              - key: client.crt
                path: client.crt
              - key: client.key
                path: client.key
            defaultMode: 256
        - name: logback
          configMap:
            defaultMode: 256
            name: cm-postgre-logback
            items:
              - key: logback.xml
                path: logback.xml
        - name: logsshare
          emptyDir: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 600