apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gw-postgre-database
spec:
  selector:
    istio: {{namespace}}-egress
  servers:
    - hosts:
        - {{postgres_host}}
      port:
        name: tcp-11111
        number: 11111
        protocol: TCP