apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gw-postgre-database
spec:
  selector:
    istio: {{namespace}}-egress
  servers:
    - hosts:
        - {{postgres_host}}
      port:
        name: tcp-{{postgres_port}}
        number: {{postgres_port}}
        protocol: TCP