kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-ignite-app-settings
  labels:
    app: {{namespace}}-ignite
data:
  eureka_host: "{{eureka_client_host}}"
  ignite_server_port: "{{ignite_server_port}}"