kind: Deployment
apiVersion: apps/v1
metadata:
  name: dp-ignite-app
  labels:
    app: {{namespace}}-ignite
  annotations:
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/proxyCPU: {{sidecar_cpu_istio_req}}
    sidecar.istio.io/proxyCPULimit: {{sidecar_cpu_istio_lim}}
    sidecar.istio.io/proxyMemory: {{sidecar_mem_istio_req}}
    sidecar.istio.io/proxyMemoryLimit: {{sidecar_mem_istio_lim}}
spec:
  replicas: {{ignite_replica_count}}
  selector:
    matchLabels:
      app: {{namespace}}-ignite
  template:
    metadata:
      labels:
        app: {{namespace}}-ignite
    spec:
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 60
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: {{ignite_cpu_limit}}
              memory: {{ignite_mem_limit}}
            requests:
              cpu: {{ignite_cpu_req}}
              memory: {{ignite_mem_req}}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ignite_server_port}}
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ignite_server_port}}
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ignite_server_port}}
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 10
          terminationMessagePath: /dev/termination-log
          name: ignite-app
          securityContext:
            readOnlyRootFilesystem: false
          envFrom:
            - configMapRef:
                name: cm-ignite-app-settings
          ports:
            - name: tcp-{{ignite_server_port}}
              containerPort: {{ignite_server_port}}
              protocol: TCP
          imagePullPolicy: Never
          volumeMounts:
            - name: logsshare
              mountPath: /mnt/logs
            - name: logback
              readOnly: true
              mountPath: /mnt/
          terminationMessagePolicy: File
          image: {{ignite_image}}
      dnsPolicy: ClusterFirst
      volumes:
        - name: logback
          configMap:
            defaultMode: 256
            name: cm-ignite-logback
            items:
              - key: logback.xml
                path: logback.xml
        - name: logsshare
          emptyDir: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 600