apiVersion: v1
data:
  mesh: |-
    accessLogEncoding: TEXT
    accessLogFile: /dev/stdout
    accessLogFormat: ""
    defaultConfig:
      concurrency: 2
      configPath: ./etc/istio/proxy
      discoveryAddress: {{istio_cp_main}}.{{istio_control_plane}}.svc:15012
      drainDuration: 45s
      parentShutdownDuration: 1m0s
      proxyAdminPort: 15000
      proxyMetadata:
        DNS_AGENT: ""
      serviceCluster: istio-proxy
      tracing:
        tlsSettings:
          caCertificates: null
          clientCertificate: null
          mode: DISABLE
          privateKey: null
          sni: null
          subjectAltNames: []
        zipkin:
          address: zipkin.{{istio_control_plane}}.svc:9411
    disableMixerHttpReports: true
    disablePolicyChecks: true
    enableAutoMtls: true
    enableEnvoyAccessLogService: false
    enablePrometheusMerge: false
    enableTracing: true
    ingressClass: istio
    ingressControllerMode: STRICT
    ingressService: istio-ingressgateway
    localityLbSetting:
      enabled: true
    outboundTrafficPolicy:
      mode: ALLOW_ANY
    protocolDetectionTimeout: 5000ms
    reportBatchMaxEntries: 100
    reportBatchMaxTime: 1s
    rootNamespace: {{istio_control_plane}}
    sdsUdsPath: unix:/etc/istio/proxy/SDS
    trustDomain: cluster.local
    trustDomainAliases: null
  meshNetworks: 'networks: {}'
kind: ConfigMap
metadata:
  name: cm-istio-basic-ingress