kind: Service
apiVersion: v1
metadata:
  name: svc-web-ingress
  labels:
    app: {{namespace}}-ingress
    deleteLabel: {{namespace}}-ingress
    product: addressbook-ingress
    istio: {{namespace}}-ingress
    type: istio-edge
spec:
  ports:
    - name: tcp-8443
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: tcp-8444
      protocol: TCP
      port: 8444
      targetPort: 8444
  selector:
    app: {{namespace}}-ingress
  type: ClusterIP
  sessionAffinity: None