- hosts: localhost
  become: no
  gather_facts: False
  strategy: free
  serial: 10
  connection: local
  vars_files:
    - vars/variables.yaml
    - vars/user-variables.yaml
  vars:
    - dev: true
  roles:
    - { role: delete_ingress, tags: ingress }
    - { role: delete_egress, tags: egress }
    - { role: delete_web, tags: web }
    - { role: delete_mongo, tags: mongo }
    - { role: delete_postgre, tags: postgre }
    - { role: delete_ignite, tags: ignite }
    - { role: delete_eureka, tags: eureka }
    - { role: delete_istio_https, tags: istio_https, when: not web_ssl_enabled | bool }