- hosts: localhost
  become: no
  gather_facts: False
  strategy: free
  serial: 10
  connection: local
  vars_files:
    - vars/variables.yaml
    - vars/user-variables.yaml
  roles:
    - { role: decrypt_secrets, tags: always }
    - { role: deploy_eureka, tags: eureka }
    - { role: deploy_fluent_bit_web, tags: fluent_bit_web, when: fluent_bit_enabled | bool }
    - { role: deploy_mongo, tags: mongo }
    - { role: deploy_postgre, tags: postgre }
    - { role: deploy_ignite, tags: ignite }
    - { role: deploy_web, tags: web }
    - { role: deploy_ingress, tags: ingress }
    - { role: deploy_egress, tags: egress }
    - { role: deploy_istio_https, tags: istio_https, when: not web_ssl_enabled | bool }
    - { role: deploy_istio_x509, tags: istio_x509, when: web_ssl_enabled | bool }
    - { role: delete_secrets, tags: always }