- hosts: localhost
  become: no
  gather_facts: False
  strategy: free
  serial: 10
  connection: local
  vars_files:
    - vars/variables.yaml
  vars:
    - dev: true
  roles:
    - { role: deploy_eureka, tags: eureka }
    - { role: deploy_mongo, tags: mongo }
    - { role: deploy_postgre, tags: postgre }
    - { role: deploy_ignite, tags: ignite }
    - { role: deploy_web, tags: web }
    - { role: deploy_ingress, tags: ingress }