apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-web-https
  namespace: {{namespace}}
  labels:
    type: istio-edge
spec:
  exportTo:
    - .
  gateways:
    - {{namespace}}-ingress
    - gw-web-ingress
  hosts:
    - {{web_istio_route_host}}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: svc-web-api
            port:
              number: {{web_server_port}}