server:
  port: ${eureka_server_port}
eureka:
  server:
    renewal-percent-threshold: 0.85
  instance:
    hostname: ${eureka_hostname}
  client:
    register-with-eureka: false
    fetch-registry: false
management:
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true