apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
{% if web_ssl_enabled %}
  name: https
{% else %}
  name: http
{% endif %}
  annotations:
    kubernetes.io/ingress.class: "nginx"
{% if web_ssl_enabled %}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
{% else %}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
{% endif %}
spec:
  rules:
    - host: {{web_route_host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-web-api
                port:
                  number: {{web_server_port}}