kind: Service
apiVersion: v1
metadata:
  name: svc-addressbook-egress
  labels:
    app: {{namespace}}-egress
    product: addressbook-egress
    type: istio-edge
spec:
  ports:
    - name: http-{{postgres_port}}
      protocol: TCP
      port: {{postgres_port}}
      targetPort: {{postgres_port}}
    - name: http-{{mongo_db_port}}
      protocol: TCP
      port: {{mongo_db_port}}
      targetPort: {{mongo_db_port}}
    - name: http-{{fluent_elasticsearch_port}}
      protocol: TCP
      port: {{fluent_elasticsearch_port}}
      targetPort: {{fluent_elasticsearch_port}}
  selector:
    app: {{namespace}}-egress