kind: Service
apiVersion: v1
metadata:
  name: svc-addressbook-egress
  labels:
    app: {{namespace}}-egress
    product: addressbook-egress
    type: istio-edge
spec:
  ports:
    - name: http-15432
      protocol: TCP
      port: 15432
      targetPort: 15432
    - name: http-15433
      protocol: TCP
      port: 15433
      targetPort: 15433
  selector:
    app: {{namespace}}-egress