kind: Service
apiVersion: v1
metadata:
  name: svc-addressbook-egress
  labels:
    app: {{namespace}}-egress
    product: addressbook-egress
    type: istio-edge
spec:
  ports:
    - name: http-11111
      protocol: TCP
      port: 11111
      targetPort: 11111
    - name: http-11112
      protocol: TCP
      port: 11112
      targetPort: 11112
  selector:
    app: {{namespace}}-egress